/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Argument { 'content' : string, 'timestamp' : Time }
export interface Debate {
  'status' : DebateStatus,
  'result' : DebateResult,
  'userSide' : Side,
  'responseLength' : string,
  'topic' : string,
  'turns' : Array<Argument>,
  'mode' : string,
  'tips' : Array<string>,
  'aiSide' : Side,
  'score' : Score,
  'category' : string,
}
export interface DebateResult { 'overallRating' : string }
export interface DebateStatus { 'name' : string, 'display' : string }
export interface Score {
  'calculatedOnOpenAi' : number,
  'overall' : number,
  'calculatedOnDfinity' : number,
}
export interface Side { 'name' : string, 'display' : string }
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'score' : Score,
  'stats' : UserStats,
  'debateHistory' : Array<Debate>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'weakestCategory' : string,
  'strongestCategory' : string,
  'winRate' : number,
  'totalDebates' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToDebateHistory' : ActorMethod<[Debate], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'fetchTopUsersByScore' : ActorMethod<[bigint], Array<UserProfile>>,
  'fetchTopUsersByWinRate' : ActorMethod<[bigint], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<[Principal], UserStats>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'makeHttpOutcall' : ActorMethod<[string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateDebateHistory' : ActorMethod<[DebateResult], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];