/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DebateStatus = IDL.Record({
  'name' : IDL.Text,
  'display' : IDL.Text,
});
export const DebateResult = IDL.Record({ 'overallRating' : IDL.Text });
export const Side = IDL.Record({ 'name' : IDL.Text, 'display' : IDL.Text });
export const Time = IDL.Int;
export const Argument = IDL.Record({
  'content' : IDL.Text,
  'timestamp' : Time,
});
export const Score = IDL.Record({
  'calculatedOnOpenAi' : IDL.Float64,
  'overall' : IDL.Float64,
  'calculatedOnDfinity' : IDL.Float64,
});
export const Debate = IDL.Record({
  'status' : DebateStatus,
  'result' : DebateResult,
  'userSide' : Side,
  'responseLength' : IDL.Text,
  'topic' : IDL.Text,
  'turns' : IDL.Vec(Argument),
  'mode' : IDL.Text,
  'tips' : IDL.Vec(IDL.Text),
  'aiSide' : Side,
  'score' : Score,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserStats = IDL.Record({
  'weakestCategory' : IDL.Text,
  'strongestCategory' : IDL.Text,
  'winRate' : IDL.Float64,
  'totalDebates' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'score' : Score,
  'stats' : UserStats,
  'debateHistory' : IDL.Vec(Debate),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToDebateHistory' : IDL.Func([Debate], [], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'fetchTopUsersByScore' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'fetchTopUsersByWinRate' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func([IDL.Principal], [UserStats], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'makeHttpOutcall' : IDL.Func([IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateDebateHistory' : IDL.Func([DebateResult], [], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DebateStatus = IDL.Record({ 'name' : IDL.Text, 'display' : IDL.Text });
  const DebateResult = IDL.Record({ 'overallRating' : IDL.Text });
  const Side = IDL.Record({ 'name' : IDL.Text, 'display' : IDL.Text });
  const Time = IDL.Int;
  const Argument = IDL.Record({ 'content' : IDL.Text, 'timestamp' : Time });
  const Score = IDL.Record({
    'calculatedOnOpenAi' : IDL.Float64,
    'overall' : IDL.Float64,
    'calculatedOnDfinity' : IDL.Float64,
  });
  const Debate = IDL.Record({
    'status' : DebateStatus,
    'result' : DebateResult,
    'userSide' : Side,
    'responseLength' : IDL.Text,
    'topic' : IDL.Text,
    'turns' : IDL.Vec(Argument),
    'mode' : IDL.Text,
    'tips' : IDL.Vec(IDL.Text),
    'aiSide' : Side,
    'score' : Score,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserStats = IDL.Record({
    'weakestCategory' : IDL.Text,
    'strongestCategory' : IDL.Text,
    'winRate' : IDL.Float64,
    'totalDebates' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'score' : Score,
    'stats' : UserStats,
    'debateHistory' : IDL.Vec(Debate),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToDebateHistory' : IDL.Func([Debate], [], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'fetchTopUsersByScore' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'fetchTopUsersByWinRate' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func([IDL.Principal], [UserStats], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'makeHttpOutcall' : IDL.Func([IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateDebateHistory' : IDL.Func([DebateResult], [], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };